/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardViewPatientsRouteImport } from './routes/dashboard/viewPatients'
import { Route as DashboardViewMedicineListRouteImport } from './routes/dashboard/viewMedicineList'
import { Route as DashboardPatientPrescriptionRouteImport } from './routes/dashboard/patientPrescription'
import { Route as DashboardAdministerUserRouteImport } from './routes/dashboard/administerUser'
import { Route as DashboardAddPatientRouteImport } from './routes/dashboard/addPatient'
import { Route as DashboardAccountSettingRouteImport } from './routes/dashboard/accountSetting'
import { Route as AuthSignUpIndexRouteImport } from './routes/_auth/signUp/index'
import { Route as AuthLoginIndexRouteImport } from './routes/_auth/login/index'
import { Route as AuthForgotPasswordIndexRouteImport } from './routes/_auth/forgotPassword/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiAdminApproveUserRouteImport } from './routes/api/admin/approve-user'

const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardViewPatientsRoute = DashboardViewPatientsRouteImport.update({
  id: '/viewPatients',
  path: '/viewPatients',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardViewMedicineListRoute =
  DashboardViewMedicineListRouteImport.update({
    id: '/viewMedicineList',
    path: '/viewMedicineList',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardPatientPrescriptionRoute =
  DashboardPatientPrescriptionRouteImport.update({
    id: '/patientPrescription',
    path: '/patientPrescription',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardAdministerUserRoute = DashboardAdministerUserRouteImport.update({
  id: '/administerUser',
  path: '/administerUser',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardAddPatientRoute = DashboardAddPatientRouteImport.update({
  id: '/addPatient',
  path: '/addPatient',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardAccountSettingRoute = DashboardAccountSettingRouteImport.update({
  id: '/accountSetting',
  path: '/accountSetting',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const AuthSignUpIndexRoute = AuthSignUpIndexRouteImport.update({
  id: '/signUp/',
  path: '/signUp/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthLoginIndexRoute = AuthLoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthForgotPasswordIndexRoute = AuthForgotPasswordIndexRouteImport.update({
  id: '/forgotPassword/',
  path: '/forgotPassword/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminApproveUserRoute = ApiAdminApproveUserRouteImport.update({
  id: '/api/admin/approve-user',
  path: '/api/admin/approve-user',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/dashboard/accountSetting': typeof DashboardAccountSettingRoute
  '/dashboard/addPatient': typeof DashboardAddPatientRoute
  '/dashboard/administerUser': typeof DashboardAdministerUserRoute
  '/dashboard/patientPrescription': typeof DashboardPatientPrescriptionRoute
  '/dashboard/viewMedicineList': typeof DashboardViewMedicineListRoute
  '/dashboard/viewPatients': typeof DashboardViewPatientsRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/admin/approve-user': typeof ApiAdminApproveUserRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/forgotPassword/': typeof AuthForgotPasswordIndexRoute
  '/login/': typeof AuthLoginIndexRoute
  '/signUp/': typeof AuthSignUpIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard/accountSetting': typeof DashboardAccountSettingRoute
  '/dashboard/addPatient': typeof DashboardAddPatientRoute
  '/dashboard/administerUser': typeof DashboardAdministerUserRoute
  '/dashboard/patientPrescription': typeof DashboardPatientPrescriptionRoute
  '/dashboard/viewMedicineList': typeof DashboardViewMedicineListRoute
  '/dashboard/viewPatients': typeof DashboardViewPatientsRoute
  '/dashboard': typeof DashboardIndexRoute
  '/api/admin/approve-user': typeof ApiAdminApproveUserRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/forgotPassword': typeof AuthForgotPasswordIndexRoute
  '/login': typeof AuthLoginIndexRoute
  '/signUp': typeof AuthSignUpIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteRouteWithChildren
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/dashboard/accountSetting': typeof DashboardAccountSettingRoute
  '/dashboard/addPatient': typeof DashboardAddPatientRoute
  '/dashboard/administerUser': typeof DashboardAdministerUserRoute
  '/dashboard/patientPrescription': typeof DashboardPatientPrescriptionRoute
  '/dashboard/viewMedicineList': typeof DashboardViewMedicineListRoute
  '/dashboard/viewPatients': typeof DashboardViewPatientsRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/admin/approve-user': typeof ApiAdminApproveUserRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_auth/forgotPassword/': typeof AuthForgotPasswordIndexRoute
  '/_auth/login/': typeof AuthLoginIndexRoute
  '/_auth/signUp/': typeof AuthSignUpIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/dashboard/accountSetting'
    | '/dashboard/addPatient'
    | '/dashboard/administerUser'
    | '/dashboard/patientPrescription'
    | '/dashboard/viewMedicineList'
    | '/dashboard/viewPatients'
    | '/dashboard/'
    | '/api/admin/approve-user'
    | '/api/auth/$'
    | '/forgotPassword/'
    | '/login/'
    | '/signUp/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard/accountSetting'
    | '/dashboard/addPatient'
    | '/dashboard/administerUser'
    | '/dashboard/patientPrescription'
    | '/dashboard/viewMedicineList'
    | '/dashboard/viewPatients'
    | '/dashboard'
    | '/api/admin/approve-user'
    | '/api/auth/$'
    | '/forgotPassword'
    | '/login'
    | '/signUp'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/dashboard'
    | '/dashboard/accountSetting'
    | '/dashboard/addPatient'
    | '/dashboard/administerUser'
    | '/dashboard/patientPrescription'
    | '/dashboard/viewMedicineList'
    | '/dashboard/viewPatients'
    | '/dashboard/'
    | '/api/admin/approve-user'
    | '/api/auth/$'
    | '/_auth/forgotPassword/'
    | '/_auth/login/'
    | '/_auth/signUp/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  ApiAdminApproveUserRoute: typeof ApiAdminApproveUserRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/viewPatients': {
      id: '/dashboard/viewPatients'
      path: '/viewPatients'
      fullPath: '/dashboard/viewPatients'
      preLoaderRoute: typeof DashboardViewPatientsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/viewMedicineList': {
      id: '/dashboard/viewMedicineList'
      path: '/viewMedicineList'
      fullPath: '/dashboard/viewMedicineList'
      preLoaderRoute: typeof DashboardViewMedicineListRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/patientPrescription': {
      id: '/dashboard/patientPrescription'
      path: '/patientPrescription'
      fullPath: '/dashboard/patientPrescription'
      preLoaderRoute: typeof DashboardPatientPrescriptionRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/administerUser': {
      id: '/dashboard/administerUser'
      path: '/administerUser'
      fullPath: '/dashboard/administerUser'
      preLoaderRoute: typeof DashboardAdministerUserRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/addPatient': {
      id: '/dashboard/addPatient'
      path: '/addPatient'
      fullPath: '/dashboard/addPatient'
      preLoaderRoute: typeof DashboardAddPatientRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/accountSetting': {
      id: '/dashboard/accountSetting'
      path: '/accountSetting'
      fullPath: '/dashboard/accountSetting'
      preLoaderRoute: typeof DashboardAccountSettingRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_auth/signUp/': {
      id: '/_auth/signUp/'
      path: '/signUp'
      fullPath: '/signUp/'
      preLoaderRoute: typeof AuthSignUpIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/login/': {
      id: '/_auth/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof AuthLoginIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/forgotPassword/': {
      id: '/_auth/forgotPassword/'
      path: '/forgotPassword'
      fullPath: '/forgotPassword/'
      preLoaderRoute: typeof AuthForgotPasswordIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/approve-user': {
      id: '/api/admin/approve-user'
      path: '/api/admin/approve-user'
      fullPath: '/api/admin/approve-user'
      preLoaderRoute: typeof ApiAdminApproveUserRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthRouteRouteChildren {
  AuthForgotPasswordIndexRoute: typeof AuthForgotPasswordIndexRoute
  AuthLoginIndexRoute: typeof AuthLoginIndexRoute
  AuthSignUpIndexRoute: typeof AuthSignUpIndexRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthForgotPasswordIndexRoute: AuthForgotPasswordIndexRoute,
  AuthLoginIndexRoute: AuthLoginIndexRoute,
  AuthSignUpIndexRoute: AuthSignUpIndexRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface DashboardRouteRouteChildren {
  DashboardAccountSettingRoute: typeof DashboardAccountSettingRoute
  DashboardAddPatientRoute: typeof DashboardAddPatientRoute
  DashboardAdministerUserRoute: typeof DashboardAdministerUserRoute
  DashboardPatientPrescriptionRoute: typeof DashboardPatientPrescriptionRoute
  DashboardViewMedicineListRoute: typeof DashboardViewMedicineListRoute
  DashboardViewPatientsRoute: typeof DashboardViewPatientsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardAccountSettingRoute: DashboardAccountSettingRoute,
  DashboardAddPatientRoute: DashboardAddPatientRoute,
  DashboardAdministerUserRoute: DashboardAdministerUserRoute,
  DashboardPatientPrescriptionRoute: DashboardPatientPrescriptionRoute,
  DashboardViewMedicineListRoute: DashboardViewMedicineListRoute,
  DashboardViewPatientsRoute: DashboardViewPatientsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  ApiAdminApproveUserRoute: ApiAdminApproveUserRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
