/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PatientDashboardRouteRouteImport } from './routes/patientDashboard/route'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PatientDashboardIndexRouteImport } from './routes/patientDashboard/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as PatientDashboardOverviewRouteImport } from './routes/patientDashboard/overview'
import { Route as PatientDashboardHistoryRouteImport } from './routes/patientDashboard/history'
import { Route as PatientDashboardAppointmentRouteImport } from './routes/patientDashboard/appointment'
import { Route as DashboardViewPatientsRouteImport } from './routes/dashboard/viewPatients'
import { Route as DashboardViewMedicineListRouteImport } from './routes/dashboard/viewMedicineList'
import { Route as DashboardPatientPrescriptionRouteImport } from './routes/dashboard/patientPrescription'
import { Route as DashboardAppointmentAvailableRouteImport } from './routes/dashboard/appointmentAvailable'
import { Route as DashboardAdministerUserRouteImport } from './routes/dashboard/administerUser'
import { Route as DashboardAddPatientRouteImport } from './routes/dashboard/addPatient'
import { Route as DashboardAccountSettingRouteImport } from './routes/dashboard/accountSetting'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AuthSignUpIndexRouteImport } from './routes/_auth/signUp/index'
import { Route as AuthRoleSelectIndexRouteImport } from './routes/_auth/roleSelect/index'
import { Route as AuthForgotPasswordIndexRouteImport } from './routes/_auth/forgotPassword/index'
import { Route as ApiCronCleanupAppointmentRouteImport } from './routes/api/cron/cleanupAppointment'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiAdminApproveUserRouteImport } from './routes/api/admin/approve-user'

const PatientDashboardRouteRoute = PatientDashboardRouteRouteImport.update({
  id: '/patientDashboard',
  path: '/patientDashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientDashboardIndexRoute = PatientDashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PatientDashboardRouteRoute,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const PatientDashboardOverviewRoute =
  PatientDashboardOverviewRouteImport.update({
    id: '/overview',
    path: '/overview',
    getParentRoute: () => PatientDashboardRouteRoute,
  } as any)
const PatientDashboardHistoryRoute = PatientDashboardHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => PatientDashboardRouteRoute,
} as any)
const PatientDashboardAppointmentRoute =
  PatientDashboardAppointmentRouteImport.update({
    id: '/appointment',
    path: '/appointment',
    getParentRoute: () => PatientDashboardRouteRoute,
  } as any)
const DashboardViewPatientsRoute = DashboardViewPatientsRouteImport.update({
  id: '/viewPatients',
  path: '/viewPatients',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardViewMedicineListRoute =
  DashboardViewMedicineListRouteImport.update({
    id: '/viewMedicineList',
    path: '/viewMedicineList',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardPatientPrescriptionRoute =
  DashboardPatientPrescriptionRouteImport.update({
    id: '/patientPrescription',
    path: '/patientPrescription',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardAppointmentAvailableRoute =
  DashboardAppointmentAvailableRouteImport.update({
    id: '/appointmentAvailable',
    path: '/appointmentAvailable',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardAdministerUserRoute = DashboardAdministerUserRouteImport.update({
  id: '/administerUser',
  path: '/administerUser',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardAddPatientRoute = DashboardAddPatientRouteImport.update({
  id: '/addPatient',
  path: '/addPatient',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardAccountSettingRoute = DashboardAccountSettingRouteImport.update({
  id: '/accountSetting',
  path: '/accountSetting',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthSignUpIndexRoute = AuthSignUpIndexRouteImport.update({
  id: '/signUp/',
  path: '/signUp/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthRoleSelectIndexRoute = AuthRoleSelectIndexRouteImport.update({
  id: '/roleSelect/',
  path: '/roleSelect/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthForgotPasswordIndexRoute = AuthForgotPasswordIndexRouteImport.update({
  id: '/forgotPassword/',
  path: '/forgotPassword/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const ApiCronCleanupAppointmentRoute =
  ApiCronCleanupAppointmentRouteImport.update({
    id: '/api/cron/cleanupAppointment',
    path: '/api/cron/cleanupAppointment',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminApproveUserRoute = ApiAdminApproveUserRouteImport.update({
  id: '/api/admin/approve-user',
  path: '/api/admin/approve-user',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/patientDashboard': typeof PatientDashboardRouteRouteWithChildren
  '/login': typeof AuthLoginRoute
  '/dashboard/accountSetting': typeof DashboardAccountSettingRoute
  '/dashboard/addPatient': typeof DashboardAddPatientRoute
  '/dashboard/administerUser': typeof DashboardAdministerUserRoute
  '/dashboard/appointmentAvailable': typeof DashboardAppointmentAvailableRoute
  '/dashboard/patientPrescription': typeof DashboardPatientPrescriptionRoute
  '/dashboard/viewMedicineList': typeof DashboardViewMedicineListRoute
  '/dashboard/viewPatients': typeof DashboardViewPatientsRoute
  '/patientDashboard/appointment': typeof PatientDashboardAppointmentRoute
  '/patientDashboard/history': typeof PatientDashboardHistoryRoute
  '/patientDashboard/overview': typeof PatientDashboardOverviewRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/patientDashboard/': typeof PatientDashboardIndexRoute
  '/api/admin/approve-user': typeof ApiAdminApproveUserRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cron/cleanupAppointment': typeof ApiCronCleanupAppointmentRoute
  '/forgotPassword/': typeof AuthForgotPasswordIndexRoute
  '/roleSelect/': typeof AuthRoleSelectIndexRoute
  '/signUp/': typeof AuthSignUpIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof AuthLoginRoute
  '/dashboard/accountSetting': typeof DashboardAccountSettingRoute
  '/dashboard/addPatient': typeof DashboardAddPatientRoute
  '/dashboard/administerUser': typeof DashboardAdministerUserRoute
  '/dashboard/appointmentAvailable': typeof DashboardAppointmentAvailableRoute
  '/dashboard/patientPrescription': typeof DashboardPatientPrescriptionRoute
  '/dashboard/viewMedicineList': typeof DashboardViewMedicineListRoute
  '/dashboard/viewPatients': typeof DashboardViewPatientsRoute
  '/patientDashboard/appointment': typeof PatientDashboardAppointmentRoute
  '/patientDashboard/history': typeof PatientDashboardHistoryRoute
  '/patientDashboard/overview': typeof PatientDashboardOverviewRoute
  '/dashboard': typeof DashboardIndexRoute
  '/patientDashboard': typeof PatientDashboardIndexRoute
  '/api/admin/approve-user': typeof ApiAdminApproveUserRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cron/cleanupAppointment': typeof ApiCronCleanupAppointmentRoute
  '/forgotPassword': typeof AuthForgotPasswordIndexRoute
  '/roleSelect': typeof AuthRoleSelectIndexRoute
  '/signUp': typeof AuthSignUpIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteRouteWithChildren
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/patientDashboard': typeof PatientDashboardRouteRouteWithChildren
  '/_auth/login': typeof AuthLoginRoute
  '/dashboard/accountSetting': typeof DashboardAccountSettingRoute
  '/dashboard/addPatient': typeof DashboardAddPatientRoute
  '/dashboard/administerUser': typeof DashboardAdministerUserRoute
  '/dashboard/appointmentAvailable': typeof DashboardAppointmentAvailableRoute
  '/dashboard/patientPrescription': typeof DashboardPatientPrescriptionRoute
  '/dashboard/viewMedicineList': typeof DashboardViewMedicineListRoute
  '/dashboard/viewPatients': typeof DashboardViewPatientsRoute
  '/patientDashboard/appointment': typeof PatientDashboardAppointmentRoute
  '/patientDashboard/history': typeof PatientDashboardHistoryRoute
  '/patientDashboard/overview': typeof PatientDashboardOverviewRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/patientDashboard/': typeof PatientDashboardIndexRoute
  '/api/admin/approve-user': typeof ApiAdminApproveUserRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cron/cleanupAppointment': typeof ApiCronCleanupAppointmentRoute
  '/_auth/forgotPassword/': typeof AuthForgotPasswordIndexRoute
  '/_auth/roleSelect/': typeof AuthRoleSelectIndexRoute
  '/_auth/signUp/': typeof AuthSignUpIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/patientDashboard'
    | '/login'
    | '/dashboard/accountSetting'
    | '/dashboard/addPatient'
    | '/dashboard/administerUser'
    | '/dashboard/appointmentAvailable'
    | '/dashboard/patientPrescription'
    | '/dashboard/viewMedicineList'
    | '/dashboard/viewPatients'
    | '/patientDashboard/appointment'
    | '/patientDashboard/history'
    | '/patientDashboard/overview'
    | '/dashboard/'
    | '/patientDashboard/'
    | '/api/admin/approve-user'
    | '/api/auth/$'
    | '/api/cron/cleanupAppointment'
    | '/forgotPassword/'
    | '/roleSelect/'
    | '/signUp/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dashboard/accountSetting'
    | '/dashboard/addPatient'
    | '/dashboard/administerUser'
    | '/dashboard/appointmentAvailable'
    | '/dashboard/patientPrescription'
    | '/dashboard/viewMedicineList'
    | '/dashboard/viewPatients'
    | '/patientDashboard/appointment'
    | '/patientDashboard/history'
    | '/patientDashboard/overview'
    | '/dashboard'
    | '/patientDashboard'
    | '/api/admin/approve-user'
    | '/api/auth/$'
    | '/api/cron/cleanupAppointment'
    | '/forgotPassword'
    | '/roleSelect'
    | '/signUp'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/dashboard'
    | '/patientDashboard'
    | '/_auth/login'
    | '/dashboard/accountSetting'
    | '/dashboard/addPatient'
    | '/dashboard/administerUser'
    | '/dashboard/appointmentAvailable'
    | '/dashboard/patientPrescription'
    | '/dashboard/viewMedicineList'
    | '/dashboard/viewPatients'
    | '/patientDashboard/appointment'
    | '/patientDashboard/history'
    | '/patientDashboard/overview'
    | '/dashboard/'
    | '/patientDashboard/'
    | '/api/admin/approve-user'
    | '/api/auth/$'
    | '/api/cron/cleanupAppointment'
    | '/_auth/forgotPassword/'
    | '/_auth/roleSelect/'
    | '/_auth/signUp/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  PatientDashboardRouteRoute: typeof PatientDashboardRouteRouteWithChildren
  ApiAdminApproveUserRoute: typeof ApiAdminApproveUserRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiCronCleanupAppointmentRoute: typeof ApiCronCleanupAppointmentRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/patientDashboard': {
      id: '/patientDashboard'
      path: '/patientDashboard'
      fullPath: '/patientDashboard'
      preLoaderRoute: typeof PatientDashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patientDashboard/': {
      id: '/patientDashboard/'
      path: '/'
      fullPath: '/patientDashboard/'
      preLoaderRoute: typeof PatientDashboardIndexRouteImport
      parentRoute: typeof PatientDashboardRouteRoute
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/patientDashboard/overview': {
      id: '/patientDashboard/overview'
      path: '/overview'
      fullPath: '/patientDashboard/overview'
      preLoaderRoute: typeof PatientDashboardOverviewRouteImport
      parentRoute: typeof PatientDashboardRouteRoute
    }
    '/patientDashboard/history': {
      id: '/patientDashboard/history'
      path: '/history'
      fullPath: '/patientDashboard/history'
      preLoaderRoute: typeof PatientDashboardHistoryRouteImport
      parentRoute: typeof PatientDashboardRouteRoute
    }
    '/patientDashboard/appointment': {
      id: '/patientDashboard/appointment'
      path: '/appointment'
      fullPath: '/patientDashboard/appointment'
      preLoaderRoute: typeof PatientDashboardAppointmentRouteImport
      parentRoute: typeof PatientDashboardRouteRoute
    }
    '/dashboard/viewPatients': {
      id: '/dashboard/viewPatients'
      path: '/viewPatients'
      fullPath: '/dashboard/viewPatients'
      preLoaderRoute: typeof DashboardViewPatientsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/viewMedicineList': {
      id: '/dashboard/viewMedicineList'
      path: '/viewMedicineList'
      fullPath: '/dashboard/viewMedicineList'
      preLoaderRoute: typeof DashboardViewMedicineListRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/patientPrescription': {
      id: '/dashboard/patientPrescription'
      path: '/patientPrescription'
      fullPath: '/dashboard/patientPrescription'
      preLoaderRoute: typeof DashboardPatientPrescriptionRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/appointmentAvailable': {
      id: '/dashboard/appointmentAvailable'
      path: '/appointmentAvailable'
      fullPath: '/dashboard/appointmentAvailable'
      preLoaderRoute: typeof DashboardAppointmentAvailableRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/administerUser': {
      id: '/dashboard/administerUser'
      path: '/administerUser'
      fullPath: '/dashboard/administerUser'
      preLoaderRoute: typeof DashboardAdministerUserRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/addPatient': {
      id: '/dashboard/addPatient'
      path: '/addPatient'
      fullPath: '/dashboard/addPatient'
      preLoaderRoute: typeof DashboardAddPatientRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/accountSetting': {
      id: '/dashboard/accountSetting'
      path: '/accountSetting'
      fullPath: '/dashboard/accountSetting'
      preLoaderRoute: typeof DashboardAccountSettingRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/signUp/': {
      id: '/_auth/signUp/'
      path: '/signUp'
      fullPath: '/signUp/'
      preLoaderRoute: typeof AuthSignUpIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/roleSelect/': {
      id: '/_auth/roleSelect/'
      path: '/roleSelect'
      fullPath: '/roleSelect/'
      preLoaderRoute: typeof AuthRoleSelectIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/forgotPassword/': {
      id: '/_auth/forgotPassword/'
      path: '/forgotPassword'
      fullPath: '/forgotPassword/'
      preLoaderRoute: typeof AuthForgotPasswordIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/api/cron/cleanupAppointment': {
      id: '/api/cron/cleanupAppointment'
      path: '/api/cron/cleanupAppointment'
      fullPath: '/api/cron/cleanupAppointment'
      preLoaderRoute: typeof ApiCronCleanupAppointmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/approve-user': {
      id: '/api/admin/approve-user'
      path: '/api/admin/approve-user'
      fullPath: '/api/admin/approve-user'
      preLoaderRoute: typeof ApiAdminApproveUserRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthRouteRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthForgotPasswordIndexRoute: typeof AuthForgotPasswordIndexRoute
  AuthRoleSelectIndexRoute: typeof AuthRoleSelectIndexRoute
  AuthSignUpIndexRoute: typeof AuthSignUpIndexRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthForgotPasswordIndexRoute: AuthForgotPasswordIndexRoute,
  AuthRoleSelectIndexRoute: AuthRoleSelectIndexRoute,
  AuthSignUpIndexRoute: AuthSignUpIndexRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface DashboardRouteRouteChildren {
  DashboardAccountSettingRoute: typeof DashboardAccountSettingRoute
  DashboardAddPatientRoute: typeof DashboardAddPatientRoute
  DashboardAdministerUserRoute: typeof DashboardAdministerUserRoute
  DashboardAppointmentAvailableRoute: typeof DashboardAppointmentAvailableRoute
  DashboardPatientPrescriptionRoute: typeof DashboardPatientPrescriptionRoute
  DashboardViewMedicineListRoute: typeof DashboardViewMedicineListRoute
  DashboardViewPatientsRoute: typeof DashboardViewPatientsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardAccountSettingRoute: DashboardAccountSettingRoute,
  DashboardAddPatientRoute: DashboardAddPatientRoute,
  DashboardAdministerUserRoute: DashboardAdministerUserRoute,
  DashboardAppointmentAvailableRoute: DashboardAppointmentAvailableRoute,
  DashboardPatientPrescriptionRoute: DashboardPatientPrescriptionRoute,
  DashboardViewMedicineListRoute: DashboardViewMedicineListRoute,
  DashboardViewPatientsRoute: DashboardViewPatientsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

interface PatientDashboardRouteRouteChildren {
  PatientDashboardAppointmentRoute: typeof PatientDashboardAppointmentRoute
  PatientDashboardHistoryRoute: typeof PatientDashboardHistoryRoute
  PatientDashboardOverviewRoute: typeof PatientDashboardOverviewRoute
  PatientDashboardIndexRoute: typeof PatientDashboardIndexRoute
}

const PatientDashboardRouteRouteChildren: PatientDashboardRouteRouteChildren = {
  PatientDashboardAppointmentRoute: PatientDashboardAppointmentRoute,
  PatientDashboardHistoryRoute: PatientDashboardHistoryRoute,
  PatientDashboardOverviewRoute: PatientDashboardOverviewRoute,
  PatientDashboardIndexRoute: PatientDashboardIndexRoute,
}

const PatientDashboardRouteRouteWithChildren =
  PatientDashboardRouteRoute._addFileChildren(
    PatientDashboardRouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  PatientDashboardRouteRoute: PatientDashboardRouteRouteWithChildren,
  ApiAdminApproveUserRoute: ApiAdminApproveUserRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiCronCleanupAppointmentRoute: ApiCronCleanupAppointmentRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
